language: cpp
compiler:
    - clang
os:
    - osx

env:
    - GAME_ENGINE_ROOT=$TRAVIS_BUILD_DIR GOOGLE_TEST_DISTRIBUTION=$GAME_ENGINE_ROOT/ThirdParty/googletest GTEST_ROOT=$GAME_ENGINE_ROOT/ThirdParty/googletest/googletest GMOCK_ROOT=$GAME_ENGINE_ROOT/ThirdParty/googletest/googlemock PROTOBUF_ROOT=$GAME_ENGINE_ROOT/ThirdParty/protobuf

before_install:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update ; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew unlink boost ; fi  # Stay cutting edge
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install boost ; fi

install:
    - ./install.sh

# Run the tests
script:
    - ./GameEngine/Networking/Chat/Test/ChatTests
