language: cpp
compiler: clang
os:
    - osx

before_install:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export CXX="/usr/local/bin/clang++-3.8 -stdlib=libc++"; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export CXXFLAGS="$CXXFLAGS -nostdinc++ -I/usr/local/opt/llvm38/lib/llvm-3.8/include/c++/v1"; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export LDFLAGS="$LDFLAGS -L/usr/local/opt/llvm38/lib/llvm-3.8/lib"; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export DYLD_LIBRARY_PATH=$BOOST_ROOT/stage/lib; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update ; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install llvm38 ; fi
    - export GAME_ENGINE_ROOT=/Users/travis/build/itsbriany/GameEngine
    - export GTEST_ROOT=$GAME_ENGINE_ROOT/ThirdParty/googletest/googletest
    - export GMOCK_ROOT=$GAME_ENGINE_ROOT/ThirdParty/googletest/googlemock
    - export GOOGLE_TEST_DISTRIBUTION=$GAME_ENGINE_ROOT/ThirdParty/googletest
    - export PROTOBUF_ROOT=$GAME_ENGINE_ROOT/ThirdParty/protobuf



install:
    - ./install.sh

# Run the tests
script:
    - ./GameEngine/Test/GameEngineTests
