language: cpp
os:
    - osx

env:
    - GAME_ENGINE_ROOT=$TRAVIS_BUILD_DIR GOOGLE_TEST_DISTRIBUTION=$GAME_ENGINE_ROOT/ThirdParty/googletest GTEST_ROOT=$GAME_ENGINE_ROOT/ThirdParty/googletest/googletest GMOCK_ROOT=$GAME_ENGINE_ROOT/ThirdParty/googletest/googlemock PROTOBUF_ROOT=$GAME_ENGINE_ROOT/ThirdParty/protobuf CXX="/usr/local/bin/clang++-3.8 -stdlib=libc++" CXXFLAGS="$CXXFLAGS -nostdinc++ -I/usr/local/opt/llvm38/lib/llvm-3.8/include/c++/v1" LDFLAGS="$LDFLAGS -L/usr/local/opt/llvm38/lib/llvm-3.8/lib" DYLD_LIBRARY_PATH=$BOOST_ROOT/stage/lib

before_install:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update ; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew unlink boost ; fi  # Stay cutting edge
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install boost ; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew unlink cmake ; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install cmake ; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew tap homebrew/versions ; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install llvm38 ; fi

install:
    - ./install.sh

# Run the tests
script:
    - ./GameEngine/Networking/Chat/Test/ChatTests
