language: cpp
compiler: clang
os:
    - osx

env:
    - GAME_ENGINE_ROOT=/Users/travis/build/itsbriany/GameEngine GOOGLE_TEST_DISTRIBUTION=$GAME_ENGINE_ROOT/ThirdParty/googletest GTEST_ROOT=$GAME_ENGINE_ROOT/ThirdParty/googletest/googletest GMOCK_ROOT=$GAME_ENGINE_ROOT/ThirdParty/googletest/googlemock PROTOBUF_ROOT=$GAME_ENGINE_ROOT/ThirdParty/protobuf

before_install:
    - echo $TRAVIS_BUILD_DIR
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export CXX="/usr/local/bin/clang++-3.9 -stdlib=libc++"; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export CXXFLAGS="$CXXFLAGS -nostdinc++ -I/usr/local/opt/llvm39/lib/llvm-3.9/include/c++/v1"; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export LDFLAGS="$LDFLAGS -L/usr/local/opt/llvm39/lib/llvm-3.9/lib"; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export DYLD_LIBRARY_PATH=$BOOST_ROOT/stage/lib; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update ; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install llvm39 ; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew unlink boost ; fi  # Stay cutting edge
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install boost ; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew unlink cmake ; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install cmake ; fi

install:
    - ./install.sh

# Run the tests
script:
    - ./GameEngine/Networking/Chat/Test/ChatTests
