language: cpp
compiler: clang
os:
    - osx
git:
    submodules: false

before_install:
    - export PHYRE_ROOT=/Users/travis/build/itsbriany/Phyre

script:
    - Tools/install.sh
    - Tools/run_tests.sh
