language: cpp
compiler:
    - clang
os:
    - osx

# Submodules are handled manually
git:
    submodules: false

before_install:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update ; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install boost ; fi

install:
    - ./install.sh

# Run the tests
script:
    - ./GameEngine/Networking/Chat/Test/ChatTests
