os: Visual Studio 2015

platform:
  - Win32

configuration:
  - Debug
  - Release

clone_folder: C:\projects\GameEngine

install:
  - ps: .\install.ps1

environment:
  MSVC_DEFAULT_OPTIONS: ON
  BOOST_ROOT: C:\Libraries\boost_1_60_0
  BOOST_LIBRARYDIR: C:\Libraries\boost_1_60_0\lib32-msvc-14.0
  GAME_ENGINE_ROOT: C:\projects\GameEngine
  GOOGLE_TEST_DISTRIBUTION: C:\projects\GameEngine\ThirdParty\googletest
  GTEST_ROOT: C:\projects\GameEngine\ThirdParty\googletest\googletest
  GMOCK_ROOT: C:\projects\GameEngine\ThirdParty\googletest\googlemock
  PROTOBUF_ROOT: C:\projects\GameEngine\ThirdParty\protobuf

build:
  parallel: true
  project: C:\projects\GameEngine\GameEngine\GameEngine.sln

test_script:
  - ps: .\run_tests.ps1
