os: Visual Studio 2015

platform:
  - Win32
  
configuration:
  - Debug

clone_folder: C:\projects\GameEngine

install:
  - install.bat

environment:
  MSVC_DEFAULT_OPTIONS: ON
  BOOST_ROOT: C:\Libraries\boost_1_59_0
  BOOST_LIBRARYDIR: C:\Libraries\boost_1_59_0\lib32-msvc-14.0
  GAME_ENGINE_ROOT: C:\projects\GameEngine
  GOOGLE_TEST_DISTRIBUTION: %GAME_ENGINE_ROOT%\googletest
  GTEST_ROOT: %GOOGLE_TEST_DISTRIBUTION%\googletest
