os: Visual Studio 2015

platform:
  - Win32

configuration:
  - Debug
  - Release

clone_folder: C:\projects\GameEngine

install:
  - install.bat

environment:
  MSVC_DEFAULT_OPTIONS: ON
  BOOST_ROOT: C:\Libraries\boost_1_60_0
  BOOST_LIBRARYDIR: C:\Libraries\boost_1_60_0\lib32-msvc-14.0
  GAME_ENGINE_ROOT: C:\projects\GameEngine
  GOOGLE_TEST_DISTRIBUTION: C:\projects\GameEngine\ThirdParty\googletest
  GTEST_ROOT: C:\projects\GameEngine\ThirdParty\googletest\googletest
  GMOCK_ROOT: C:\projects\GameEngine\ThirdParty\googletest\googlemock
  PROTOBUF_ROOT: C:\projects\GameEngine\ThirdParty\protobuf

# The tests need to dynamically link to the appropriate configuration of gmock.dll
before_build:
  - cmd: set PATH=%PATH%;%GMOCK_ROOT%\%CONFIGURATION%\;

build:
  parallel: false
  project: C:\projects\GameEngine\GameEngine\GameEngine.sln

test_script:
  - cmd: C:\projects\GameEngine\GameEngine\Networking\Test\%CONFIGURATION%\NetworkingTests.exe
