os: Visual Studio 2015

platform:
  - Win32

configuration:
  - Debug
  - Release

clone_folder: C:\projects\Phyre

install:
  - ps: .\install.ps1

environment:
  MSVC_DEFAULT_OPTIONS: ON
  BOOST_ROOT: C:\Libraries\boost_1_60_0
  BOOST_LIBRARYDIR: C:\Libraries\boost_1_60_0\lib64-msvc-14.0
  PHYRE_ROOT: C:\projects\Phyre

build:
  parallel: true
  project: C:\projects\Phyre\Build\Phyre.sln

test_script:
  - ps: .\run_tests.ps1