os: Visual Studio 2015

platform:
  - Win64

configuration:
  - Debug
  - Release

clone_folder: C:\projects\Phyre

environment:
  MSVC_DEFAULT_OPTIONS: ON
  BOOST_ROOT: C:\Libraries\boost_1_60_0
  BOOST_LIBRARYDIR: C:\Libraries\boost_1_60_0\lib64-msvc-14.0
  PHYRE_ROOT: C:\projects\Phyre
  VULKAN_ROOT: C:\VulkanSDK\1.0.39.1
  PYTHON_PATH: C:\Python35
  PYTHON_PACKAGE_PATH: C:\Python35\Scripts

install:
  - ps: (new-object net.webclient).DownloadFile('https://vulkan.lunarg.com/sdk/home#sdk/downloadConfirm/1.0.39.1/windows/VulkanSDK-1.0.39.1-Installer.exe', 'vulkan.msi')
  - ps: msiexec /i vulkan.msi /quiet /qn /norestart /log install.log
  - cmd: Tools\install.bat

test_script:
  - cmd: C:\projects\Phyre\Build\%CONFIGURATION%\PhyreTests.exe %PHYRE_ROOT%\phyre.json