os: Visual Studio 2015

environment:
  MSVC_DEFAULT_OPTIONS: ON
  BOOST_ROOT: C:\Libraries\boost_1_59_0
  BOOST_LIBRARYDIR: C:\Libraries\boost_1_59_0\lib64-msvc-14.0
  
clone_folder: C:\projects\GameEngine

before_build:
  - cmd: cd C:\projects\GameEngine
  
build:
  project: C:\projects\GameEngine\GameEngine\GameEngine.sln
